presubmits:
  - name: presubmit-from-local
    decorate: true
    always_run: true
    spec:
      containers:
      - image: alpine
        command:
        - /bin/ls
        args:
        - -ll
  - name: pre-test-infra-validate-local
    annotations:
    labels:
    run_if_changed: '^config/prow/((plugins|config).yaml|jobs/)'
    skip_report: false
    decorate: true
    cluster: default
    spec:
      containers:
        - image: "gcr.io/k8s-prow/checkconfig:v20230322-fad14aa00d"
          command:
            - "checkconfig"
          args:
            - "--plugin-config=config/prow/plugins.yaml"
            - "--config-path=config/prow/config.yaml"
