prowjob_namespace: prow
pod_namespace: test-pods

in_repo_config:
  enabled:
    "*": true

deck:
 spyglass:
   lenses:
   - lens:
       name: metadata
     required_files:
     - started.json|finished.json
   - lens:
       config:
       name: buildlog
     required_files:
     - build-log.txt
   - lens:
       name: junit
     required_files:
     - .*/junit.*\.xml
   - lens:
       name: podinfo
     required_files:
     - podinfo.json

plank:
  job_url_prefix_config:
    "*": https://prow.nephew.io/view/
  report_templates:
    '*': >-
        [Full PR test history](https://prow.nephew.io/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}).
        [Your PR dashboard](https://prow.nephew.io/pr?query=is:pr+state:open+author:{{with
        index .Spec.Refs.Pulls 0}}{{.Author}}{{end}}).
  default_decoration_configs:
    "*":
      gcs_configuration:
        bucket: s3://prow-logs
        path_strategy: explicit
      s3_credentials_secret: s3-credentials
      utility_images:
        clonerefs: gcr.io/k8s-prow/clonerefs:v20230322-fad14aa00d
        entrypoint: gcr.io/k8s-prow/entrypoint:v20230322-fad14aa00d
        initupload: gcr.io/k8s-prow/initupload:v20230322-fad14aa00d
        sidecar: gcr.io/k8s-prow/sidecar:v20230322-fad14aa00d

tide:
  queries:
  - labels:
    - lgtm
    - approved
    missingLabels:
    - needs-rebase
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - do-not-merge/invalid-owners-file
    orgs:
    - radochm
labelconfig:
  presets:
    prow:
      - name: lgtm
        color: 00ff00
      - name: do-not-merge
        color: ff0000
      - name: needs-rebse
        color: ff6600

branch-protection:
  orgs:
    radochm:
      protect: true
      required_status_checks:
        contexts:
        - EasyCLA
      exclude:
        - "^dependabot/"

decorate_all_jobs: true
periodics:
- interval: 6m
  agent: kubernetes
  name: echo-test
  spec:
    containers:
    - image: alpine
      command: ["/bin/date"]
presubmits:
  radochm:
  - name: validate-prow-inrepoconfig
    always_run: true
    decorate: true
    extra_refs:
    - org: radochm
      repo: build-test
      base_ref: main
    spec:
      containers:
      - image: gcr.io/k8s-prow/checkconfig:v20230322-fad14aa00d
        command:
          - /ko-app/checkconfig
        args:
        - --plugin-config=plugins.yaml
        - --config-path=config.yaml
        - --prow-yaml-repo-name=$(REPO_OWNER)/$(REPO_NAME)
