prowjob_namespace: prow
pod_namespace: test-pods

in_repo_config:
  enabled:
    "*": true

deck:
 spyglass:
   lenses:
   - lens:
       name: metadata
     required_files:
     - started.json|finished.json
   - lens:
       config:
       name: buildlog
     required_files:
     - build-log.txt
   - lens:
       name: junit
     required_files:
     - .*/junit.*\.xml
   - lens:
       name: podinfo
     required_files:
     - podinfo.json

plank:
  job_url_prefix_config:
    "*": https://prow.nephew.io/view/
  report_templates:
    '*': >-
        [Full PR test history](https://prow.nephew.io/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}).
        [Your PR dashboard](https://prow.nephew.io/pr?query=is:pr+state:open+author:{{with
        index .Spec.Refs.Pulls 0}}{{.Author}}{{end}}).
  default_decoration_configs:
    "*":
      gcs_configuration:
        bucket: s3://prow-logs
        path_strategy: explicit
      s3_credentials_secret: s3-credentials
      utility_images:
        clonerefs: gcr.io/k8s-prow/clonerefs:v20230322-fad14aa00d
        entrypoint: gcr.io/k8s-prow/entrypoint:v20230322-fad14aa00d
        initupload: gcr.io/k8s-prow/initupload:v20230322-fad14aa00d
        sidecar: gcr.io/k8s-prow/sidecar:v20230322-fad14aa00d

tide:
  queries:
  - labels:
    - lgtm
    - approved
    missingLabels:
    - needs-rebase
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - do-not-merge/invalid-owners-file
    orgs:
    - radochm
 
decorate_all_jobs: true

branch-protection:
  orgs:
    radochm:
      repos:
        build-test:
          protect: true
          restrictions:
            teams: ["oncall-team"]
          required_status_checks:
            contexts:
            - EasyCLA

presubmits:
  radochm/build-test:
  - name: presubmit-from-config
    decorate: true
    always_run: true
    spec:
      containers:
      - image: alpine
        command:
        - /bin/ls
        args:
        - -ll
  - name: pre-test-infra-validate-job
    annotations:
    labels:
    run_if_changed: '.prow.yaml|.prow/'
    skip_report: false
    decorate: true
    cluster: default
    extra_refs:
      - org: radochm
        repo: prow-infra
        path_alias: github.com/radochm/prow-infra
        base_ref: main
    spec:
      containers:
        - image: "gcr.io/k8s-prow/checkconfig:v20230322-fad14aa00d"
          command:
            - "checkconfig"
          args:
            - "--plugin-config=../prow-infra/config/prow/plugins.yaml"
            - "--config-path=../prow-infra/config/prow/config.yaml"
            - "--prow-yaml-repo-name=$(REPO_OWNER)/$(REPO_NAME)"
periodics:
- cron: "55 * * * *"  # Every hour at 54 minutes past the hour
  name: infra-branchprotector
  cluster: default
  labels:
    app: branchprotector
  decorate: true
  decoration_config:
    timeout: 5h
  extra_refs:
  - org: radochm
    repo: prow-infra
    base_ref: main
  spec:
    containers:
    - name: branchprotector
      image: gcr.io/k8s-prow/branchprotector:v20230322-fad14aa00d
      command:
      - branchprotector
      args:
      - --config-path=../prow-infra/config/prow/config.yaml
      - --github-token-path=/etc/github/github-token
      - --confirm
      - --github-endpoint=http://ghproxy.default.svc.cluster.local
      - --github-endpoint=https://api.github.com
      volumeMounts:
      - name: github-token
        mountPath: /etc/github
        readOnly: true
    volumes:
    - name: github-token
      secret:
        secretName: github-token
  annotations:
    description: Runs Prow's branchprotector to apply configured GitHub status context requirements and merge policies.
