plugins:
  radochm:
    plugins:
    - approve
    - assign
    - blunderbuss
    - help
    - hold
    - invalidcommitmsg
    - label
    - lgtm
    - sigmention
    - trigger
    - verify-owners
    - wip
  radochm/prow-infra:
    plugins:
    - cat
    - config-updater
    - dog

config_updater:
  maps:
    config/prow/config.yaml:
      name: config
      namespace: prow
    config/prow/plugins.yaml:
      name: plugins
      namespace: prow
    config/prow/jobs/**/*.yaml:
      name: job-config
      namespace: prow
    config/prow/labels.yaml:
      name: label-config
      namespace: prow
