periodics:
    - name: test-periodics
      annotations:
      labels:
      cron: "30 * * * 1-5"
      skip_report: false
      decorate: true
      cluster: default
      extra_refs:
        - org: radochm
          repo: build-test
          path_alias: github.com/radochm/build-test
          base_ref: main
      spec:
        containers:
          - image: "alpine"
            command:
              - "/bin/ls"
            args:
              - "-lha"
