presubmits:
  radochm/build-test:
    - name: pre-test-infra-bootstrap
      labels:
      run_if_changed: '*.go'
      skip_report: false
      decorate: true
      cluster: default
      max_concurrency: 10
      branches:
        - ^master$
        - ^main$
      spec:
        containers:
          - image: alpine
            command:
              - "/bin/ls"
            args:
              - "-lha"
            resources:
              requests:
                memory: 1.5Gi
                cpu: 1
